name: Build docker image

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    strategy:
      matrix:
        image:
          - debian
          - debian-slim
          - alpine
          - alpine-slim

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          make ${{ matrix.image }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push images
        run: |
          docker images --format "{{.Repository}}" | grep weechat | \
          while read image
          do
            docker push "${image}"
          done
